# Default values for bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: bookinfo-production
  #hostname: ocpeng-bookinfo.ia.com
  podAnnotations:
    CMDB_ID: AL19428
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: 100m
    sidecar.istio.io/proxyCPULimit: 100m
    sidecar.istio.io/proxyMemory: 120M
    sidecar.istio.io/proxyMemoryLimit: 120M
  labels:
    CMDB_ID: AL19428    

details:
  image:
    tag: 1.18.0

productpage:
  image:
    tag: 1.18.0

ratings:
  image:
    tag: 1.18.0

reviews:
  image:
    tag: 1.18.0

istio-config:
  gateway:
    port:
      number: 8443
      name: https
      protocol: https
    tls:
      mode: MUTUAL
      credentialName: bookinfo-tls
      cipherSuites:
        - "ECDHE-RSA-AES256-GCM-SHA384"
        - "ECDHE-ECDSA-AES256-GCM-SHA384"
        - "ECDHE-RSA-AES128-GCM-SHA256"
        - "ECDHE-ECDSA-AES128-GCM-SHA256"
      minProtocolVersion: TLSV1_2
      maxProtocolVersion: TLSV1_3

  destinationRule:
    productpage:
      trafficPolicy:
        loadBalancer:
          simple: LEAST_REQUEST
      subsets:
      - name: v1
        labels:
          version: v1
        trafficPolicy:
          loadBalancer:
            simple: ROUND_ROBIN

    details:
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2

    reviews:
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
      - name: v3
        labels:
          version: v3

    ratings:
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
      - name: v2-mysql
        labels:
          version: v2-mysql
      - name: v2-mysql-vm
        labels:
          version: v2-mysql-vm