# Default values for bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: lbg-prel-bookinfo-001-pb
  hostname: ocpeng-bookinfo.ia.com
  podAnnotations:
    CMDB_ID: AL19428
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: 100m
    sidecar.istio.io/proxyCPULimit: 100m
    sidecar.istio.io/proxyMemory: 120M
    sidecar.istio.io/proxyMemoryLimit: 120M
  labels:
    CMDB_ID: AL19428    

gateway:
  name: bookinfo-gateway
  selector: ingressgateway
  port: 443
  tls:
    mode: SIMPLE
    secretName: bookinfo-tls
    cipherSuites:
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDHE-ECDSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES128-GCM-SHA256"
    - "ECDHE-ECDSA-AES128-GCM-SHA256"
    min: TLSV1_2
    max: TLSV1_3

virtualService:
  name: bookinfo

namespacePolicy:
  defaultDeny: true
  mtlsMode: STRICT

authorizations:
  bookinfo-productpage:
    matchLabels:
      app: productpage
    rules:
    - allowPrincipals:
      - istio-system/istio-ingressgateway-service-account
      paths:
      - /productpage
      - /static/*
      - /login
      - /logout
      - /api/v1/products

  bookinfo-details:
    matchLabels:
      app: details
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /details/*

  bookinfo-reviews:
    matchLabels:
      app: reviews
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /reviews/*
