apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookinfo-project-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Project contains bookinfo application
  destinations:
  - name: in-cluster
    namespace: bookinfo-production
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/glaceroy/bookinfo