apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-production
  namespace: argocd
  labels:
    app-type: bookinfo-production
spec:
  destination:
    namespace: bookinfo-production
    server: https://kubernetes.default.svc
  project: bookinfo-project-prod
  source:
    path: production/
    repoURL: https://github.com/glaceroy/bookinfo
    targetRevision: HEAD
    helm:
      version: v3
      valuesFile:
        - production/helm-config/values.yaml
  info:
    - name: 'Purpose'
      value: 'Application to test istio use cases'
  syncPolicy:
    automated: {}
