# Default values for details.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The overall system your service is a part of
system: bookinfo
# The name of your service
service: reviews

# The versions for your service
version:
- v1
- v2
- v3

# The number of pod replicas to run for your service
replicaCount: 1

# Environment Variables
env:
  LOG_DIR: /tmp/logs

# Docker settings
image:
  # The name of your docker container
  repository: docker.io/istio/examples-bookinfo-reviews
  # Your docker container's tag
  tag: latest
  imagePullPolicy: IfNotPresent

# Istio uses the service account name as a component of the service's security
# identity. Set "create" to false to use an previously created service account.
serviceAccount:
  create: true
  name: bookinfo-reviews

# Port settings
# Ports must be named <protocol>[-<suffix>] to work with Istio.
# Valid protocols are grpc, http, http2, https, mongo, mysql, redis, tcp, tls, udp
ports:
- name: http
  port: 9080
  targetPort: 9080

# Resource settings (use Kubernetes syntax)
resources: 
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 55Mi

# Volume and mounts 
volumes:
- name: wlp-output
  emptyDir: {}
- name: tmp
  emptyDir: {}
    
volumeMounts:
- name: tmp
  mountPath: /tmp
- name: wlp-output
  mountPath: /opt/ibm/wlp/output