# Default values for istio-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  name: bookinfo-gateway
  selector: ingressgateway
  port:
    number: 8080
    name: http
    protocol: HTTP

virtualService:
  name: bookinfo-virtualservice

authorizations:
  productpage:
    matchLabels:
      app: productpage
    rules:
    - allowPrincipals:
      - istio-system/istio-ingressgateway-service-account
      paths:
      - /productpage
      - /static/*
      - /login
      - /logout
      - /api/v1/products

  details:
    matchLabels:
      app: details
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /details/*

  reviews:
    matchLabels:
      app: reviews
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /reviews/*