# Default values for istio-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  name: bookinfo-gateway
  selector: ingressgateway
  port:
    number: 8080
    name: http
    protocol: HTTP

authorizations:
  productpage:
    matchLabels:
      app: productpage
    rules:
    - allowPrincipals:
      - istio-system/istio-ingressgateway-service-account
      paths:
      - /productpage
      - /static/*
      - /login
      - /logout
      - /api/v1/products

  details:
    matchLabels:
      app: details
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /details/*

  reviews:
    matchLabels:
      app: reviews
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /reviews/*

destinationRule:
  productpage:
    subsets:
    - name: v1
      labels:
        version: v1

  details:
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

  reviews:
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3

  ratings:
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v2-mysql
      labels:
        version: v2-mysql
    - name: v2-mysql-vm
      labels:
        version: v2-mysql-vm

virtualService:
  productpage:
    http:
    - route:
      - destination:
          host: productpage
          subset: v1

  details:
    http:
    - route:
      - destination:
          host: details
          subset: v1

  reviews:
    http:
    - route:
      - destination:
          host: reviews
          subset: v1

  ratings:
    http:
    - route:
      - destination:
          host: ratings
          subset: v1

