# Default values for istio-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  name: bookinfo-gateway
  selector: ingressgateway
  port:
    number: 8080
    name: http
    protocol: HTTP

virtualService:
  name: bookinfo-virtualservice

namespacePolicy:
  defaultDeny: true
  mtlsMode: STRICT

authorizations:
  productpage:
    matchLabels:
      app: productpage
    rules:
    - allowPrincipals:
      - istio-system/istio-ingressgateway-service-account
      paths:
      - /productpage
      - /static/*
      - /login
      - /logout
      - /api/v1/products

  details:
    matchLabels:
      app: details
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /details/*

  reviews:
    matchLabels:
      app: reviews
    rules:
    - allowPrincipals:
      - bookinfo-productpage
      paths:
      - /reviews/*

destinationRule:
  productpage:
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
    subsets:
    - name: v1
      labels:
        version: v1

  details:
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

  reviews:
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3

  ratings:
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v2-mysql
      labels:
        version: v2-mysql
    - name: v2-mysql-vm
      labels:
        version: v2-mysql-vm


