# Default values for bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: bookinfo-development
  #hostname: ocpeng-bookinfo.ia.com
  podAnnotations:
    CMDB_ID: AL19428
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: 100m
    sidecar.istio.io/proxyCPULimit: 100m
    sidecar.istio.io/proxyMemory: 120M
    sidecar.istio.io/proxyMemoryLimit: 120M
  labels:
    CMDB_ID: AL19428    

destinationRule:
  productpage:
    subsets:
    - name: v1
      labels:
        version: v1

  details:
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

  reviews:
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3

  ratings:
    subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v2-mysql
      labels:
        version: v2-mysql
    - name: v2-mysql-vm
      labels:
        version: v2-mysql-vm
