# Default values for bookinfo development.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: bookinfo-development
  #hostname: ocpeng-bookinfo.ia.com
  podAnnotations:
    CMDB_ID: AL19428
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: 100m
    sidecar.istio.io/proxyCPULimit: 100m
    sidecar.istio.io/proxyMemory: 120M
    sidecar.istio.io/proxyMemoryLimit: 120M
  labels:
    CMDB_ID: AL19428    

istio-config:
  destinationRule:
    productpage:
      trafficPolicy:
        loadBalancer:
          simple: LEAST_REQUEST
      subsets:
      - name: v1
        labels:
          version: v1
        trafficPolicy:
          loadBalancer:
            simple: ROUND_ROBIN

    details:
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2

    reviews:
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
      - name: v3
        labels:
          version: v3

    ratings:
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
      - name: v2-mysql
        labels:
          version: v2-mysql
      - name: v2-mysql-vm
        labels:
          version: v2-mysql-vm

  virtualService:
    productpage:
      http:
      - route:
        - destination:
            host: productpage
            subset: v1

    details:
      http:
      - route:
        - destination:
            host: details
            subset: v1

    reviews:
      http:
      - route:
        - destination:
            host: reviews
            subset: v1
          weight: 25
        - destination:
            host: reviews
            subset: v2
          weight: 25
        - destination:
            host: reviews
            subset: v3
          weight: 50

    ratings:
      http:
      - route:
        - destination:
            host: ratings
            subset: v1
        - destination:
            host: ratings
            subset: v2
