{{- range $key, $spec := .Values.authorizations }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $key | lower | quote }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    matchLabels:
{{- toYaml $spec.matchLabels | nindent 6 }}
  rules:
  {{- range $rule := $spec.rules }}
  - from:
    - source:
        principals: 
        {{- range $principal := $rule.allowPrincipals}}
        {{- if contains "/" $principal }}
        {{- $splits := split "/" $principal }}
        - {{ (print "cluster.local/ns/" $splits._0 "/sa/" $splits._1) | quote }}
        {{- else }}
        - {{ (print "cluster.local/ns/" $.Values.global.namespace "/sa/" $principal) | quote }}
        {{- end }}
        {{- end }}
    {{- if $rule.paths }}
    to:
    - operation:
        paths:
        {{- range $rule.paths }}
        - {{.}}
        {{- end }}
    {{ end }}
  {{- end }}
---
{{- end }}