{{- range $key, $spec := .Values.destinationRule }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $key | lower }}-dr
  namespace: {{ $.Values.global.namespace }}
spec:
  host: {{ $key | lower }}
{{- if not ($spec | empty)  }}
{{ toYaml $spec | indent 2 }}
{{- end }}
---
{{- end }}