{{- range $key, $spec := .Values.virtualService }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $key | lower }}
  namespace: {{ $.Values.global.namespace }}
spec:
  hosts:
  - {{ $key | lower }}
{{- if not ($spec | empty)  }}
{{ toYaml $spec | indent 2 }}
{{- end }}
---
{{- end }}