---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ (split "-" .Release.Name)._0 }}-vs
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
  - {{ .Values.global.hostname | default "*" | quote }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /productpage
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080