---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    istio: {{ .Values.gateway.selector }}
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.global.namespace}}/{{ .Values.global.hostname }}
    tls:
      mode: {{ .Values.gateway.tls.mode }}
      credentialName: {{ .Values.gateway.tls.secretName }}
      cipherSuites:
      {{- range $.Values.gateway.tls.cipherSuites }}
        - {{ . }}
      {{- end }}
      minProtocolVersion: {{ .Values.gateway.tls.min }}
      maxProtocolVersion: {{ .Values.gateway.tls.max }}

