apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service }}
    service: {{ .Values.service }}
spec:
  ports:
  {{- range .Values.ports }}
  - name: {{ .name | quote }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.service }}
